name: oneApi-windows
description: Install Intel oneAPI
inputs:
  icx:
    description: Is the icx compiler required
    required: false
    default: false
  ifx:
    description: Is the ifx compiler required
    required: false
    default: false
  mkl:
    description: Is the mkl library required
    required: false
    default: false

runs:
  using: composite
  steps:
  - name: Set Windows and Linux CPP Components
    run: |
      WINDOWS_CPP_COMPONENTS=""
      LINUX_CPP_COMPONENTS=""
      if [ "${{ inputs.icx }}" == "true" ]; then
        WINDOWS_CPP_COMPONENTS="${WINDOWS_CPP_COMPONENTS}intel.oneapi.win.cpp-dpcpp-common:"
        LINUX_CPP_COMPONENTS="${LINUX_CPP_COMPONENTS}intel-oneapi-dpcpp-cpp-compiler:"
      fi
      if [ "${{ inputs.ifx }}" == "true" ]; then
        WINDOWS_CPP_COMPONENTS="${WINDOWS_CPP_COMPONENTS}intel.oneapi.win.ifort-compiler:"
        LINUX_CPP_COMPONENTS="${LINUX_CPP_COMPONENTS}intel-oneapi-compiler-fortran:"
      fi
      if [ "${{ inputs.mkl }}" == "true" ]; then
        WINDOWS_CPP_COMPONENTS="${WINDOWS_CPP_COMPONENTS}intel.oneapi.win.mkl.devel:"
        LINUX_CPP_COMPONENTS="${LINUX_CPP_COMPONENTS}intel.oneapi.lin.mkl.devel:"
      fi
      echo "WINDOWS_CPP_COMPONENTS=${WINDOWS_CPP_COMPONENTS%:}" >> $GITHUB_ENV
      echo "LINUX_CPP_COMPONENTS=${LINUX_CPP_COMPONENTS%:}" >> $GITHUB_ENV
    shell: bash
  - name: Install Intel oneAPI Windows
    if: runner.os == 'Windows'
    uses: worc4021/oneApi-windows@v1
    with:
      WINDOWS_CPP_COMPONENTS: ${{ env.WINDOWS_CPP_COMPONENTS }}
  - name: Install Intel oneAPI Linux
    if: runner.os == 'Linux'
    uses: worc4021/oneApi-linux@v1
    with:
      LINUX_CPP_COMPONENTS: ${{ env.LINUX_CPP_COMPONENTS }}