name: oneApi-windows
description: Install Intel oneAPI
inputs:
  icx:
    description: Is the icx compiler required
    required: false
    default: false
  ifx:
    description: Is the ifx compiler required
    required: false
    default: false
  mkl:
    description: Is the mkl library required
    required: false
    default: false

runs:
  using: composite
  steps:
  - name: Install Intel oneAPI Windows
    if: runner.os == 'Windows'
    uses: worc4021/oneApi-windows@v1
    with:
      WINDOWS_CPP_COMPONENTS: ${{ join([inputs.icx == 'true' && 'intel.oneapi.win.cpp-dpcpp-common', inputs.ifx == 'true' && 'intel.oneapi.win.ifort-compiler', inputs.mkl == 'true' && 'intel.oneapi.win.mkl.devel'], ':') }}
  - name: Install Intel oneAPI Linux
    if: runner.os == 'Linux'
    uses: worc4021/oneApi-linux@v1
    with:
      LINUX_CPP_COMPONENTS: ${{ join([inputs.icx == 'true' && 'intel-oneapi-dpcpp-cpp-compiler', inputs.ifx == 'true' && 'intel-oneapi-compiler-fortran', inputs.mkl == 'true' && 'intel.oneapi.lin.mkl.devel '], ':') }}